#4 챌린지 등록하기 화면 구현
UMC-beilsang/beilsang-iOS pull request #34
Opened 2024-02-04 14:49 UTC by kwaktato

등록하기 화면 구현

RegisterFirst, Second, Third ViewController
하나의 뷰에서 세 개의 뷰로 나눠짐에 따라 세 개의 VC로 나눠서 구현
isNext, isAgree 배열 이용해 모든 필드가 다 채워져야 다음으로 버튼, 만들기 버튼 활성화
상단의 < 버튼을 누르면 챌린지 등록하기 취소를 위한 알림 팝업창 띄워짐
하단의 이전 버튼 누르면 이전 화면의 viewcontroller 나옴

RegisterFirstViewController: 챌린지 등록하기 첫번째 화면 구현
이미지 피커 사용으로 사진 등록하기 기능 추가, 이미지의 X버튼 누르면 이미지 없어짐
실천 기간 선택 전에는 실천 횟수 지정 버튼 사용 불가능, 실천 기간 선택하면 안내 레이블 추가

RegisterSecondViewController: 챌린지 등록하기 두번째 화면
이미지 피커 사용
유의사항 등록하기 버튼은 collection view를 이용해 구현(레이아웃의 height 설정 문제로 안 나왔던 것 같음. noticeLables가 바뀌면 height를 업데이트 해줘야함. noticeRegisterButtonEnabled() 함수에 구현)

RegisterThirdViewController: 챌린지 등록하기 세번째 화면
체크 버튼 모두 누르면 만들기 버튼 활성화되고, 누르면 챌린지 등록하기 팝업창 띄우기
체크 버튼 옆의 레이블 눌러도 체크되도록 구현(버튼이랑 레이블 모두 같은 action으로 연결) 

RegisterModalViewController: 챌린지 등록하기 두번째 화면에서 "챌린지 유의사항 등록하기"를 누르면 나오는 모달창
모달창 띄워지고, 모달창의 텍스트 필드를 누르면 키보드가 모달창 아래로 나오는 기능
등록하기 버튼 누르면 텍스트필드의 텍스트를 noticeLabels 배열에 추가, 모달창 닫기
모달창 외의 부분을 누르면 모달창 닫기

RegisterCompleteViewController: 챌린지 등록하기 완료하면 띄워지는 화면
"홈으로", "챌린지 보기" 버튼 존재

추가 구현해야 하는 부분: 텍스트 필드 누르면 파란색, 빨간색, 유효성 검사(피그마의 "입력" 부분)

2024-02-04 15:24 UTC, 30isdead approved these changes
그래도 다른 VC들이 막 어렵진 않은데 서로 연결이 어려울것같구만. . . .
글고 로직 구현하느라 고생했어 ㅠ ㅠ 나한테도 알려줘서 고마움
고생했습니다~!!!
어디서 컨플릭트 낫는지는 모르겠군

2024-02-04 15:24 UTC, 30isdead commented on beilsang/beilsang/Model/Utility/Color+.swift
> +    static let beBGPop = UIColor(hex: "#222222")
색상 추가 감사합니다~

2024-02-04 16:07 UTC, 633jinn requested changes
은채양 pbxproj에 아직 conflict 해결 못한것 가타용

2024-02-06 01:08 UTC, 633jinn approved these changes
발견 부분 merge하고 approve하려고 해서 conflict 났길래 제가 그냥 했슴다!
수고했어~~~~~

2024-02-06 01:08 UTC, 633jinn commented on beilsang/beilsang.xcodeproj/project.pbxproj
> +<<<<<<< feature/home-register
command + f 로 "=="이거 검색해서 하면 편해용

2024-02-06 09:41 UTC, merged